### PR TITLE
Upgrade to .net 8.0

### PR DESCRIPTION
**Pull request by MauNguyenVan**
Hello,
I am glad to contribute to this project

### CODE REVIEW

**Comment by denxorz** [comment]
Thanks for the help! I think changing AnimationLength to AnimationDuration would be a breaking change. Can you elaborate on that change?

For now, I made the update a separate commit.

**Comment by denxorz** [comment]
> > Thanks for the help! I think changing AnimationDuration to AnimationDuration would be a breaking change. Can you elaborate on that change?
> 
> I just think "animation duration" is the more accurate term when referring to the total time an animation takes to complete, and the project has not actived so long time, thus maybe no one is using it. I decided to change for more clearly.

I agree that the name is better, but I do not like just breaking things. Preferably we add the `AnimationDuration` and make the `AnimationDuration` obsolete, so older projects still work. 

Not sure about "actived so long time", it is not much, but Nuget says it averaged 1 download a day over de last 7 years.

**Comment by denxorz** [comment]
> By the way, the two first links in read me are died

Thanks, should be fixed now.

**Comment by denxorz** [comment]
Can you make separate PRs for the different things you need? That makes it easier to review and test.

**Comment by MauNguyenVan** [comment]
> I agree that the name is better, but I do not like just breaking things. Preferably we add the `AnimationDuration` and make the `AnimationDuration` obsolete, so older projects still work.
> 
> Not sure about "actived so long time", it is not much, but Nuget says it averaged 1 download a day over de last 7 years.

I know it is a breaking change, but currently, the project is quite small  
 and I want to make this control become more flexible as a core control for "Zooming and Panning" 
 then use this as a core control to build other wraping controls for some specifc purposes like : Autocad, Image viewer, Visual Seletion.

I don't want to fork the project. And you to continue managing as the original author

**Pull request closed without merging**
